source 'https://github.com/CocoaPods/Specs.git'

workspace 'PodspecTest'
project 'PodspecTest.xcodeproj'

use_frameworks!

target :'PodspecTest' do
	pod 'ZDCSyncable', path: '../', :inhibit_warnings => false
end
