source 'https://github.com/CocoaPods/Specs.git'

workspace 'TestPodspecObjC'
project 'TestPodspecObjC.xcodeproj'

use_frameworks!

target :'TestPodspecObjC' do
	pod 'ZDCSyncable/ObjC', path: '../../', :inhibit_warnings => false
end